# Permalinks
permalink:        pretty

# Setup
url:              http://arthurdouillard.com

# Set to '' in case of hosting on `http://<your-github-name>.github.io`
baseurl:        ''

title:            Arthur Douillard

# Markdown enabled, however don't use more than one paragraph (enforced by `>`)
description:      >
  I'm Arthur Douillard, and here is my blog.

# The tags listed as entries in the sidebar
sidebar_tags:     [python, ml]

# Fallback image and color if not overwritten for tag or post
image:            
color:            '#1E90FF'

author:
  name:           'Arthur Douillard'
  twitter:        Ar_Douillard
  github:         mougatine
  photo:          /public/img/douill_a.jpg

  # Markdown enabled, can use multiple paragraphs (enabled by `|`)
  about:          |
    FIXME About.
